# Generated by Django 6.0.6 on 2026-08-31 18:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0036_evaluationmanager'),
        ('formbuilder', '0008_finish_submission_send_migration'),
        ('members', '0006_parentclaim_submitted_by_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerEvaluation',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='club.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_received', to='members.member', verbose_name='player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_evaluations', to='club.season', verbose_name='season')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_evaluation', to='formbuilder.submission', verbose_name='submission')),
            ],
            options={
                'verbose_name': 'player evaluation',
                'verbose_name_plural': 'player evaluations',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationSettings',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='club.club')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_settings_for', to='formbuilder.form', verbose_name='form')),
            ],
            options={
                'verbose_name': 'evaluation settings',
                'verbose_name_plural': 'evaluation settings',
                'constraints': [models.UniqueConstraint(fields=('club',), name='unique_evaluation_settings_per_club')],
            },
        ),
    ]
