# Generated by Django 6.0.6 on 2026-09-09 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_evaluation_checklists'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluationchecklist',
            options={'ordering': ['name'], 'verbose_name': 'evaluation checklist', 'verbose_name_plural': 'evaluation checklists'},
        ),
        migrations.RemoveField(
            model_name='evaluationchecklist',
            name='order',
        ),
    ]
