# Generated by Django 6.0.6 on 2026-09-09 08:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0038_clubmembership_club_clubme_club_id_646d5d_idx_and_more'),
        ('evaluations', '0004_alter_evaluationchecklist_options_and_more'),
        ('members', '0006_parentclaim_submitted_by_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationNote',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField(verbose_name='note')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_notes_authored', to='members.member', verbose_name='author')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='evaluations.evaluationchecklist', verbose_name='checklist')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='club.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_notes', to='members.member', verbose_name='player')),
            ],
            options={
                'verbose_name': 'evaluation note',
                'verbose_name_plural': 'evaluation notes',
                'ordering': ['-created'],
            },
        ),
    ]
