# Generated by Django 6.0.6 on 2026-09-12 10:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0038_clubmembership_club_clubme_club_id_646d5d_idx_and_more'),
        ('evaluations', '0005_evaluationnote'),
        ('members', '0007_family_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationSession',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='ended at')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='evaluations.evaluationchecklist', verbose_name='checklist')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='club.club')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='members.member', verbose_name='started by')),
            ],
            options={
                'verbose_name': 'evaluation session',
                'verbose_name_plural': 'evaluation sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationOutcome',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.TextField(verbose_name='decision')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='club.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_outcomes', to='members.member', verbose_name='player')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='members.member', verbose_name='recorded by')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='evaluations.evaluationsession', verbose_name='session')),
            ],
            options={
                'verbose_name': 'evaluation outcome',
                'verbose_name_plural': 'evaluation outcomes',
                'ordering': ['player__last_name', 'player__first_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='evaluationsession',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('checklist',), name='one_open_evaluation_session_per_checklist'),
        ),
        migrations.AddConstraint(
            model_name='evaluationoutcome',
            constraint=models.UniqueConstraint(fields=('session', 'player'), name='unique_outcome_per_session_per_player'),
        ),
    ]
