# Generated by Django 6.0.6 on 2026-07-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='management_position',
            field=models.BooleanField(default=False, verbose_name='management position'),
        ),
    ]
