# Generated by Django 6.0.6 on 2026-08-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_position_created_position_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='management_position',
            field=models.BooleanField(default=False, help_text='A staff position with management authority over the team (e.g. head coach) -- requires staff position to also be checked.', verbose_name='management position'),
        ),
        migrations.AlterField(
            model_name='position',
            name='staff_position',
            field=models.BooleanField(default=False, help_text='Coach, manager, physio, ... -- assignable via a StaffAssignment rather than a team roster spot.', verbose_name='staff position'),
        ),
    ]
