# Generated by Django 6.0.6 on 2026-08-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_position_management_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=0, help_text="Lower numbers are listed first (e.g. on a team's roster). Positions with the same number are ordered by name.", verbose_name='ordering'),
        ),
    ]
