# Generated by Django 6.0.6 on 2026-08-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_refereelevel_refereeprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='referee_management',
            field=models.CharField(choices=[('club', 'Club'), ('federation', 'Federation')], default='club', help_text="Who arranges referees for this team's home games. Federation-managed teams are left out of the referee tools entirely -- no eligibility, no assignment, nothing to configure.", max_length=20, verbose_name='referee management'),
        ),
    ]
