# Generated by Django 6.0.6 on 2026-08-20 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_alter_team_options_alter_teammembership_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='refereelevel',
            name='inherits_from',
            field=models.ForeignKey(blank=True, help_text='A referee holding this level is also eligible for everything the linked level covers (and, transitively, whatever that one inherits from).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inherited_by', to='teams.refereelevel', verbose_name='inherits from'),
        ),
    ]
