# Generated by Django 6.0.6 on 2026-08-20 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_refereelevel_inherits_from'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refereelevel',
            options={'ordering': ['name'], 'verbose_name': 'referee level', 'verbose_name_plural': 'referee levels'},
        ),
        migrations.RemoveField(
            model_name='refereelevel',
            name='ordering',
        ),
    ]
