# Generated by Django 6.0.6 on 2026-08-29 09:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0034_clubmembership_early_payment_deadline_and_more'),
        ('teams', '0012_alter_refereelevel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberPool',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('min_number', models.PositiveSmallIntegerField(verbose_name='minimum number')),
                ('max_number', models.PositiveSmallIntegerField(verbose_name='maximum number')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='club.club')),
            ],
            options={
                'verbose_name': 'number pool',
                'verbose_name_plural': 'number pools',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='team',
            name='pool',
            field=models.ForeignKey(blank=True, help_text="Jersey numbers are checked for clashes against every other team sharing this pool, not just this one. Left blank, this team's numbers are only checked against itself, as before.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='teams.numberpool', verbose_name='number pool'),
        ),
        migrations.CreateModel(
            name='NumberReservation',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveSmallIntegerField(verbose_name='number')),
                ('note', models.CharField(blank=True, help_text='e.g. "Retired -- Jane Doe, #23".', max_length=255, verbose_name='note')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='club.club')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='teams.numberpool', verbose_name='pool')),
                ('reserved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='number_reservations', to=settings.AUTH_USER_MODEL, verbose_name='reserved by')),
            ],
            options={
                'verbose_name': 'number reservation',
                'verbose_name_plural': 'number reservations',
                'ordering': ['pool', 'number'],
            },
        ),
        migrations.AddConstraint(
            model_name='numberpool',
            constraint=models.UniqueConstraint(fields=('club', 'name'), name='unique_number_pool_name_per_club'),
        ),
        migrations.AddConstraint(
            model_name='numberreservation',
            constraint=models.UniqueConstraint(fields=('pool', 'number'), name='unique_number_per_pool_reservation'),
        ),
    ]
