# Generated by Django 6.0.6 on 2026-08-31 08:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0035_club_payment_instructions'),
        ('members', '0006_parentclaim_submitted_by_user'),
        ('teams', '0013_numberpool_team_pool_numberreservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='official_management',
            field=models.CharField(choices=[('club', 'Club'), ('federation', 'Federation')], default='club', help_text="Who arranges match officials for this team's home games. Federation-managed teams are left out of the officials tools entirely -- no eligibility, no assignment, nothing to configure.", max_length=20, verbose_name='official management'),
        ),
        migrations.CreateModel(
            name='OfficialLevel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='club.club')),
                ('inherits_from', models.ForeignKey(blank=True, help_text='An official holding this level is also eligible for everything the linked level covers (and, transitively, whatever that one inherits from).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inherited_by', to='teams.officiallevel', verbose_name='inherits from')),
                ('teams', models.ManyToManyField(blank=True, help_text="Members holding this level can be assigned as an official for these teams' home games.", related_name='official_levels', to='teams.team', verbose_name='qualifies for')),
            ],
            options={
                'verbose_name': 'official level',
                'verbose_name_plural': 'official levels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OfficialProfile',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valid_until', models.DateField(blank=True, help_text="Once this date has passed, the official is not eligible for assignment until it's extended.", null=True, verbose_name='valid until')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='officials', to='teams.officiallevel', verbose_name='level')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='official_profile', to='members.member', verbose_name='member')),
            ],
            options={
                'verbose_name': 'official profile',
                'verbose_name_plural': 'official profiles',
                'ordering': ['member__last_name', 'member__first_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='officiallevel',
            constraint=models.UniqueConstraint(fields=('club', 'name'), name='unique_official_level_name_per_club'),
        ),
    ]
