# Generated by Django 6.0.6 on 2026-09-10 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_team_official_management_officiallevel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='age_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='maximum age'),
        ),
        migrations.AddField(
            model_name='team',
            name='age_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='minimum age'),
        ),
        migrations.AddField(
            model_name='team',
            name='feeds_into',
            field=models.ForeignKey(blank=True, help_text="The team this one's players typically graduate to next season -- used to suggest call-ups from here when adding players to that team.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeder_teams', to='teams.team', verbose_name='feeds into'),
        ),
    ]
