# Generated by Django 6.0.6 on 2026-09-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0017_refereeprofile_officialprofile_club_scoping'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberpool',
            name='min_age_gap_years',
            field=models.PositiveSmallIntegerField(default=5, help_text='Two players can share a number in this pool only when born at least this many years apart. Set to 0 to never allow sharing.', verbose_name='minimum age gap (years)'),
        ),
    ]
