# Generated by Django 6.0.6 on 2026-09-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0018_numberpool_min_age_gap_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberpool',
            name='min_age_gap_years',
            field=models.PositiveSmallIntegerField(default=5, help_text='Players born at least this many years apart may share a number. 0 = never shared.', verbose_name='minimum age gap (years)'),
        ),
    ]
