# Generated by Django 6.0.6 on 2026-07-12 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_alter_clubmembership_unique_together_and_more'),
        ('events', '0001_initial'),
        ('members', '0002_alter_familymembership_unique_together_and_more'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='excluded_members',
            field=models.ManyToManyField(blank=True, related_name='excluded_from_events', to='members.member', verbose_name='excluded members'),
        ),
        migrations.AddField(
            model_name='event',
            name='invited_members',
            field=models.ManyToManyField(blank=True, related_name='invited_to_events', to='members.member', verbose_name='invited members'),
        ),
        migrations.AddField(
            model_name='event',
            name='season',
            field=models.ForeignKey(blank=True, help_text='Season whose team rosters define the audience; derived from the start date when left blank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='club.season', verbose_name='season'),
        ),
        migrations.AddField(
            model_name='event',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='scheduled_events', to='teams.team', verbose_name='teams'),
        ),
    ]
