# Generated by Django 6.0.6 on 2026-07-12 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_copy_team_to_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='team',
        ),
    ]
