# Generated by Django 6.0.6 on 2026-07-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventseries',
            name='deadline_offset',
            field=models.DurationField(blank=True, help_text="How long before the start each occurrence's sign-up deadline is.", null=True, verbose_name='deadline offset'),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='gathering_offset',
            field=models.DurationField(blank=True, help_text="How long before the start each occurrence's gathering time is.", null=True, verbose_name='gathering offset'),
        ),
    ]
