# Generated by Django 6.0.6 on 2026-07-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_series_offsets'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventseries',
            name='until',
            field=models.DateTimeField(blank=True, help_text="Series end: no occurrences are generated after this. Leave blank for open-ended (bounded by the rule's own COUNT/UNTIL, if any).", null=True, verbose_name='until'),
        ),
    ]
