# Generated by Django 6.0.6 on 2026-08-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_attendance_created_attendance_modified_event_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='showed_up',
            field=models.BooleanField(blank=True, default=None, help_text='Recorded by a check-in, separate from the RSVP status above. Blank means no check-in has been recorded yet.', null=True, verbose_name='showed up'),
        ),
    ]
