# Generated by Django 6.0.6 on 2026-08-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0017_club_season_duration_months_club_season_start'),
        ('events', '0010_attendance_showed_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_home',
            field=models.BooleanField(default=False, help_text="The club's own ground, set from the control panel -- lets an event's location tell a home game from an away one.", verbose_name='home location'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(condition=models.Q(('is_home', True)), fields=('club',), name='unique_home_location_per_club'),
        ),
    ]
