# Generated by Django 6.0.6 on 2026-08-04 09:45

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_location_is_home_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='country'),
        ),
    ]
