# Generated by Django 6.0.6 on 2026-08-04 21:22

from django.db import migrations


def create_competiton_group(apps, schema_editor):
    Competition = apps.get_model("events", "Competition")
    
    try:
        Competition.objects.create(name="RBIHF", module="events.competition.hockey")
        Competition.objects.create(name="CEHL", module="events.competition.hockey")
    
    except:
        pass


def remove_competiton_group(apps, schema_editor):
    Competition = apps.get_model("events", "Competition")
    
    try:
        Competition.objects.get(name="RBIHF", module="events.competition.hockey").delete()
        Competition.objects.get(name="CEHL", module="events.competition.hockey")
    
    except:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0016_competition'),
    ]
    
    operations = [migrations.RunPython(create_competiton_group, remove_competiton_group)]
