# Generated by Django 6.0.6 on 2026-08-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_eventreferee_external_name_eventreferee_fee_and_more'),
        ('members', '0004_group_groupmembership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='club_wide',
            field=models.BooleanField(default=False, help_text="Invite every active club member for this event's season, instead of specific teams/groups. Can't be combined with teams or groups.", verbose_name='whole club'),
        ),
        migrations.AddField(
            model_name='event',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Invite every current member of these groups.', related_name='scheduled_events', to='members.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='club_wide',
            field=models.BooleanField(default=False, help_text="Invite every active club member for each occurrence's season, instead of specific teams/groups. Can't be combined with teams or groups.", verbose_name='whole club'),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Invite every current member of these groups.', related_name='event_series', to='members.group', verbose_name='groups'),
        ),
    ]
