# Generated by Django 6.0.6 on 2026-08-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_event_club_wide_event_groups_eventseries_club_wide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='deadline_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text="Set once events.tasks.send_deadline_reminders has nudged whoever still hasn't answered -- keeps that job from reminding the same event twice.", null=True, verbose_name='deadline reminder sent at'),
        ),
    ]
