# Generated by Django 6.0.6 on 2026-08-22 14:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_lineup_lineupunit_lineupslot'),
        ('members', '0006_parentclaim_submitted_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineupunit',
            name='lineup',
        ),
        migrations.CreateModel(
            name='LineupSelection',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='events.lineup', verbose_name='line-up')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_selections', to='members.member', verbose_name='member')),
            ],
            options={
                'verbose_name': 'line-up selection',
                'verbose_name_plural': 'line-up selections',
            },
        ),
        migrations.DeleteModel(
            name='LineupSlot',
        ),
        migrations.DeleteModel(
            name='LineupUnit',
        ),
        migrations.AddConstraint(
            model_name='lineupselection',
            constraint=models.UniqueConstraint(fields=('lineup', 'member'), name='unique_selection_per_lineup_per_member'),
        ),
    ]
