# Generated by Django 6.0.6 on 2026-08-22 14:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_remove_lineupunit_lineup_lineupselection_and_more'),
        ('members', '0006_parentclaim_submitted_by_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefereeSignup',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('invited', 'invited'), ('accepted', 'accepted'), ('declined', 'declined')], default='invited', max_length=20, verbose_name='status')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='responded at')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referee_signups', to='events.event', verbose_name='event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referee_signups', to='members.member', verbose_name='member')),
            ],
            options={
                'verbose_name': 'referee sign-up',
                'verbose_name_plural': 'referee sign-ups',
                'ordering': ['event', 'member__last_name', 'member__first_name'],
                'constraints': [models.UniqueConstraint(fields=('event', 'member'), name='unique_referee_signup_per_event_per_member')],
            },
        ),
    ]
