# Generated by Django 6.0.6 on 2026-08-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_refereesignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='scheduled_publish_at',
            field=models.DateTimeField(blank=True, help_text='If set (and not yet published), this line-up publishes itself automatically at this time -- events.tasks.publish_scheduled_lineups is the periodic sweep that catches it.', null=True, verbose_name='scheduled publish at'),
        ),
    ]
