# Generated by Django 6.0.6 on 2026-08-31 08:58

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_lineup_scheduled_publish_at'),
        ('members', '0006_parentclaim_submitted_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_officials',
            field=models.PositiveSmallIntegerField(default=2, help_text='How many match officials can be assigned to this game. Only meaningful for home games -- ignored otherwise.', verbose_name='max officials'),
        ),
        migrations.CreateModel(
            name='EventTask',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('needed_quantity', models.PositiveSmallIntegerField(default=1, help_text='How many people/families need to take this on.', verbose_name='needed quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='members.member', verbose_name='created by')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='events.event', verbose_name='event')),
            ],
            options={
                'verbose_name': 'event task',
                'verbose_name_plural': 'event tasks',
                'ordering': ['event', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventOfficial',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_name', models.CharField(blank=True, help_text="For an official who isn't a club member (e.g. federation-appointed) -- logged by name only.", max_length=255, verbose_name='external official name')),
                ('fee', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='fee')),
                ('km', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='kilometers')),
                ('km_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Reimbursement rate per kilometer, e.g. 0.4230.', max_digits=6, null=True, verbose_name='rate per km')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='members.member', verbose_name='assigned by')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officials', to='events.event', verbose_name='event')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='official_assignments', to='members.member', verbose_name='member')),
            ],
            options={
                'verbose_name': 'event official',
                'verbose_name_plural': 'event officials',
                'ordering': ['event', 'member__last_name', 'member__first_name'],
                'constraints': [models.UniqueConstraint(fields=('event', 'member'), name='unique_official_per_event'), models.CheckConstraint(condition=models.Q(models.Q(('member__isnull', False), ('external_name', '')), models.Q(('member__isnull', True), models.Q(('external_name', ''), _negated=True)), _connector='OR'), name='event_official_member_xor_external_name')],
            },
        ),
        migrations.CreateModel(
            name='EventTaskClaim',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claimed_at', models.DateTimeField(auto_now_add=True, verbose_name='claimed at')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_task_claims', to='members.member', verbose_name='member')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='events.eventtask', verbose_name='task')),
            ],
            options={
                'verbose_name': 'event task claim',
                'verbose_name_plural': 'event task claims',
                'ordering': ['task', 'claimed_at'],
                'constraints': [models.UniqueConstraint(fields=('task', 'member'), name='unique_claim_per_member_per_task')],
            },
        ),
        migrations.CreateModel(
            name='OfficialSignup',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('invited', 'invited'), ('accepted', 'accepted'), ('declined', 'declined')], default='invited', max_length=20, verbose_name='status')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='responded at')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_signups', to='events.event', verbose_name='event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_signups', to='members.member', verbose_name='member')),
            ],
            options={
                'verbose_name': 'official sign-up',
                'verbose_name_plural': 'official sign-ups',
                'ordering': ['event', 'member__last_name', 'member__first_name'],
                'constraints': [models.UniqueConstraint(fields=('event', 'member'), name='unique_official_signup_per_event_per_member')],
            },
        ),
    ]
