# Generated by Django 6.0.6 on 2026-08-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_event_max_officials_eventtask_eventofficial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_friendly',
            field=models.BooleanField(default=False, help_text="A friendly game doesn't count towards the standings.", verbose_name='friendly'),
        ),
    ]
