# Generated by Django 6.0.6 on 2026-08-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_event_is_friendly'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='live_score_polling_done_at',
            field=models.DateTimeField(blank=True, help_text="Set once the per-minute score poller has seen this game go live and then come back off live -- i.e. it's finished, so there's no point calling the data source again for the rest of the polling window.", null=True, verbose_name='live score polling done at'),
        ),
    ]
