# Generated by Django 6.0.6 on 2026-08-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_create_officials_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_officials',
            field=models.PositiveSmallIntegerField(default=1, help_text='How many match officials can be assigned to this game. Only meaningful for a home game/tournament -- ignored otherwise.', verbose_name='max officials'),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_referees',
            field=models.PositiveSmallIntegerField(default=2, help_text='How many referees can be assigned to this game. Only meaningful for a home game/tournament -- ignored otherwise.', verbose_name='max referees'),
        ),
    ]
