# Generated by Django 6.0.6 on 2026-09-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0038_clubmembership_club_clubme_club_id_646d5d_idx_and_more'),
        ('events', '0033_backfill_game_titles_home_away'),
        ('members', '0006_parentclaim_submitted_by_user'),
        ('teams', '0014_team_official_management_officiallevel_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['event', 'status'], name='events_atte_event_i_e8472a_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['club', 'start'], name='events_even_club_id_097b4b_idx'),
        ),
    ]
