# Generated by Django 6.0.6 on 2026-09-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_attendance_events_atte_event_i_e8472a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='competition_label',
            field=models.CharField(blank=True, help_text="Tells apart multiple competitions a team plays in via the same source, e.g. “Division 1” vs “Cup” -- purely a display label, unlike competition itself, which fetch_game_info matches against a Competition row's name.", max_length=100, verbose_name='competition label'),
        ),
        migrations.AddField(
            model_name='event',
            name='external_source_id',
            field=models.CharField(blank=True, help_text="Which of that data source's own entries this game came from -- e.g. RBIHF gives a team a separate page per competition it plays in, so this is that page's team id. Set automatically by the importer; scopes re-imports so one competition's import never deletes another's games for the same team. Blank for anything not imported, or imported before this field existed.", max_length=255, verbose_name='external source ID'),
        ),
    ]
