# Generated by Django 6.0.6 on 2026-09-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_event_competition_label_event_external_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='external_source_id',
            field=models.CharField(blank=True, help_text="Which of that data source's own entries this game came from -- e.g. RBIHF's own team id for the page it was scraped from. Set by the importer; scopes re-imports so one competition never deletes another's games.", max_length=255, verbose_name='external source ID'),
        ),
    ]
