# Generated by Django 6.0.6 on 2026-08-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_plan_options_alter_planprice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='due',
            name='last_reminder_level',
            field=models.CharField(blank=True, editable=False, max_length=20, verbose_name='last reminder level'),
        ),
        migrations.AddField(
            model_name='due',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='last reminder sent at'),
        ),
    ]
