# Generated by Django 6.0.6 on 2026-08-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_due_last_reminder_level_due_last_reminder_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at'),
        ),
    ]
