# Generated by Django 6.0.6 on 2026-09-05 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_plan_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='sent at'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='sent by'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sent_method',
            field=models.CharField(blank=True, choices=[('email', 'emailed'), ('manual', 'marked as sent')], max_length=10, verbose_name='sent method'),
        ),
    ]
