# Generated by Django 6.0.6 on 2026-09-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_invoice_sent_at_invoice_sent_by_invoice_sent_method'),
        ('club', '0037_club_vat_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='due',
            index=models.Index(fields=['status', 'grace_until'], name='billing_due_status_23dbc8_idx'),
        ),
    ]
