# Generated by Django 6.0.6 on 2026-08-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_backfill_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(help_text='Supports Markdown: **bold**, *italic*, [link text](https://example.com), # heading, - list item, > quote. Rendered to HTML for the public website; shown as plain text here in the control panel.', verbose_name='body'),
        ),
    ]
