# Generated by Django 6.0.6 on 2026-08-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='notified_at',
            field=models.DateTimeField(blank=True, help_text='When the audience notification was sent -- or, if the publisher opted out of notifying, set immediately at publish time so the sweep never sends one.', null=True, verbose_name='notified at'),
        ),
    ]
