# Generated by Django 6.0.6 on 2026-08-25 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsphoto',
            name='focal_x',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='focal point (x)'),
        ),
        migrations.AddField(
            model_name='newsphoto',
            name='focal_y',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='focal point (y)'),
        ),
    ]
