# Generated by Django 6.0.6 on 2026-08-28 13:11

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newsphoto_focal_x_newsphoto_focal_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsphoto',
            name='image',
            field=models.ImageField(max_length=255, upload_to=news.models.news_photo_path, verbose_name='image'),
        ),
    ]
