# Generated by Django 6.0.6 on 2026-09-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_newsphoto_image_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(help_text='Supports Markdown: **bold**, *italic*, [link text](https://example.com), # heading, - list item, > quote, | table | header |. Rendered to HTML for the public website; shown as plain text here in the control panel.', verbose_name='body'),
        ),
    ]
