# Generated by Django 6.0.6 on 2026-09-09 17:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('club', models.CharField(max_length=150, verbose_name='club')),
                ('members', models.PositiveIntegerField(blank=True, null=True, verbose_name='members')),
                ('role', models.CharField(choices=[('board_secretary', 'Board / secretary'), ('treasurer', 'Treasurer'), ('coach_manager', 'Coach / team manager'), ('federation', 'Federation'), ('other', 'Something else')], max_length=20, verbose_name='role')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('plan_interest', models.CharField(blank=True, max_length=20, verbose_name='plan interest')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='user agent')),
            ],
            options={
                'verbose_name': 'contact request',
                'verbose_name_plural': 'contact requests',
                'ordering': ['-created'],
            },
        ),
    ]
