# Generated by Django 6.0.6 on 2026-08-21 08:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0029_duesinvoice'),
        ('members', '0006_parentclaim_submitted_by_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.URLField(max_length=500, unique=True, verbose_name='endpoint')),
                ('p256dh', models.CharField(max_length=255, verbose_name='p256dh key')),
                ('auth', models.CharField(max_length=255, verbose_name='auth key')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='user agent')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='club.club')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='members.member', verbose_name='member')),
            ],
            options={
                'verbose_name': 'push subscription',
                'verbose_name_plural': 'push subscriptions',
                'ordering': ['-created'],
            },
        ),
    ]
