# Generated by Django 6.0.6 on 2026-08-27 12:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0034_clubmembership_early_payment_deadline_and_more'),
        ('shop', '0023_product_min_registrants_and_more'),
        ('teams', '0012_alter_refereelevel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationBatch',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_first_name', models.CharField(max_length=150, verbose_name='contact first name')),
                ('contact_last_name', models.CharField(max_length=150, verbose_name='contact last name')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='contact email')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='contact phone')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='subtotal')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text="The immediate (min-registrants) portion only -- an early-payment discount isn't confirmed until paid, see ClubMembership.early_payment_discount.", max_digits=10, verbose_name='discount amount')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='club.club')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registration_batches', to='club.season', verbose_name='season')),
                ('submitted_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_batches', to=settings.AUTH_USER_MODEL, verbose_name='submitted by')),
            ],
            options={
                'verbose_name': 'registration batch',
                'verbose_name_plural': 'registration batches',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationDetails',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_kind', models.CharField(choices=[('player', 'player'), ('volunteer', 'volunteer')], default='player', max_length=20, verbose_name='entry kind')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text="This entry's own share of the batch subtotal, before any discount.", max_digits=10, verbose_name='price')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text="This entry's own share of the batch's immediate (min-registrants) discount.", max_digits=10, verbose_name='discount amount')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='registration.registrationbatch', verbose_name='batch')),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_details', to='club.clubmembership', verbose_name='membership')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_requests', to='shop.productvariant', verbose_name='product variant')),
                ('requested_position', models.ForeignKey(blank=True, limit_choices_to={'staff_position': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_requests', to='teams.position', verbose_name='requested position')),
                ('requested_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_requests', to='teams.team', verbose_name='requested team')),
                ('resulting_staff_assignment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_details', to='teams.staffassignment', verbose_name='resulting staff assignment')),
            ],
            options={
                'verbose_name': 'registration details',
                'verbose_name_plural': 'registration details',
                'ordering': ['batch', 'created'],
            },
        ),
    ]
