# Generated by Django 6.0.6 on 2026-08-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdetails',
            name='entry_kind',
            field=models.CharField(choices=[('player', 'Player'), ('volunteer', 'Volunteer')], default='player', max_length=20, verbose_name='entry kind'),
        ),
    ]
