# Generated by Django 6.0.6 on 2026-08-28 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0034_clubmembership_early_payment_deadline_and_more'),
        ('registration', '0002_alter_registrationdetails_entry_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdetails',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_details', to='club.clubmembership', verbose_name='membership'),
        ),
    ]
