# Generated by Django 6.0.6 on 2026-08-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_registrationbatch_status_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdetails',
            name='requested_jersey_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='requested jersey number'),
        ),
    ]
