# Generated by Django 6.0.6 on 2026-08-30 19:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0035_club_payment_instructions'),
        ('registration', '0005_registrationdetails_requested_jersey_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationbatch',
            name='invoice_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='invoice due date'),
        ),
        migrations.AddField(
            model_name='registrationbatch',
            name='invoice_last_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='invoice last reminder sent at'),
        ),
        migrations.AddField(
            model_name='registrationbatch',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='invoice number'),
        ),
        migrations.AddField(
            model_name='registrationbatch',
            name='invoice_reminder_count',
            field=models.PositiveIntegerField(default=0, verbose_name='invoice reminders sent'),
        ),
        migrations.AddField(
            model_name='registrationbatch',
            name='invoice_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='invoice sent at'),
        ),
        migrations.AddField(
            model_name='registrationbatch',
            name='manual_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='An extra discount staff can apply when confirming the invoice, on top of any multi-registrant discount.', max_digits=10, verbose_name='manual discount amount'),
        ),
        migrations.AddField(
            model_name='registrationbatch',
            name='manual_discount_note',
            field=models.CharField(blank=True, help_text="Shown as the discount's own label on the invoice, e.g. “Loyalty discount”. Falls back to a generic label when left blank.", max_length=255, verbose_name='manual discount note'),
        ),
        migrations.AddField(
            model_name='registrationdetails',
            name='excluded_from_invoice',
            field=models.BooleanField(default=False, verbose_name='excluded from invoice'),
        ),
        migrations.AddConstraint(
            model_name='registrationbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_number', ''), _negated=True), fields=('club', 'invoice_number'), name='unique_registration_invoice_number_per_club'),
        ),
    ]
