# Generated by Django 6.0.6 on 2026-08-30 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_registrationbatch_invoice_due_date_and_more'),
        ('teams', '0013_numberpool_team_pool_numberreservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdetails',
            name='resulting_team_membership',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_details', to='teams.teammembership', verbose_name='resulting team membership'),
        ),
    ]
