# Generated by Django 6.0.6 on 2026-09-06 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0038_clubmembership_club_clubme_club_id_646d5d_idx_and_more'),
        ('registration', '0007_registrationdetails_resulting_team_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='registrationbatch',
            index=models.Index(fields=['club', 'invoice_sent_at'], name='registratio_club_id_bf3867_idx'),
        ),
    ]
