# Generated by Django 6.0.6 on 2026-07-11 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_family_name_alter_familymembership_family_and_more'),
        ('club', '0005_alter_clubmembership_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FamilyMembership',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
