# Generated by Django 6.0.6 on 2026-07-12 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0001_initial'),
        ('members', '0002_alter_familymembership_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='formbuilder.field', verbose_name='field'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='members.member', verbose_name='member'),
        ),
    ]
