# Generated by Django 6.0.6 on 2026-07-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0002_alter_answer_field_alter_submission_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='key',
            field=models.SlugField(verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='form',
            name='slug',
            field=models.SlugField(verbose_name='slug'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('submission', 'field'), name='unique_answer_per_field_per_submission'),
        ),
        migrations.AddConstraint(
            model_name='field',
            constraint=models.UniqueConstraint(fields=('form', 'key'), name='unique_field_key_per_form'),
        ),
    ]
