# Generated by Django 6.0.6 on 2026-07-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0003_fix_tenant_uniqueness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='key',
            field=models.SlugField(blank=True, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='form',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='slug'),
        ),
    ]
