# Generated by Django 6.0.6 on 2026-08-26 22:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0033_club_shop_open_shopmanager'),
        ('formbuilder', '0005_answer_created_answer_modified_field_created_and_more'),
        ('members', '0006_parentclaim_submitted_by_user'),
        ('teams', '0012_alter_refereelevel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSend',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('club_wide', models.BooleanField(default=False, help_text="Send to every active club member for this send's season, instead of specific teams/groups. Can't be combined with teams or groups.", verbose_name='whole club')),
                ('opens_at', models.DateTimeField(blank=True, null=True, verbose_name='opens at')),
                ('closes_at', models.DateTimeField(blank=True, null=True, verbose_name='closes at')),
                ('max_submissions_per_user', models.PositiveIntegerField(blank=True, null=True, verbose_name='max submissions per user')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active?')),
                ('reminder_sent_at', models.DateTimeField(blank=True, help_text="Set once formbuilder.tasks.send_form_reminders has nudged whoever still hasn't responded -- keeps that job from reminding the same send twice.", null=True, verbose_name='reminder sent at')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='club.club')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_sends_created', to='members.member', verbose_name='created by')),
                ('excluded_members', models.ManyToManyField(blank=True, related_name='excluded_from_form_sends', to='members.member', verbose_name='excluded members')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends', to='formbuilder.form', verbose_name='form')),
                ('groups', models.ManyToManyField(blank=True, help_text='Send to every current member of these groups.', related_name='form_sends', to='members.group', verbose_name='groups')),
                ('invited_members', models.ManyToManyField(blank=True, related_name='invited_to_form_sends', to='members.member', verbose_name='invited members')),
                ('season', models.ForeignKey(blank=True, help_text='Season whose rosters define the audience; derived from the current season when blank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_sends', to='club.season', verbose_name='season')),
                ('teams', models.ManyToManyField(blank=True, related_name='form_sends', to='teams.team', verbose_name='teams')),
            ],
            options={
                'verbose_name': 'form send',
                'verbose_name_plural': 'form sends',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='send',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='formbuilder.formsend', verbose_name='send'),
        ),
    ]
