# Generated by Django 6.0.6 on 2026-08-26 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0007_backfill_formsend_from_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='closes_at',
        ),
        migrations.RemoveField(
            model_name='form',
            name='max_submissions_per_user',
        ),
        migrations.RemoveField(
            model_name='form',
            name='opens_at',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='form',
        ),
        migrations.AlterField(
            model_name='form',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Whether this form can still be picked when creating a new send. Doesn't affect sends already out.", verbose_name='is active?'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='send',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='formbuilder.formsend', verbose_name='send'),
        ),
    ]
