# Generated by Django 6.0.6 on 2026-08-31 18:59

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0008_finish_submission_send_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='value',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='value'),
        ),
    ]
