# Generated by Django 6.0.6 on 2026-09-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0009_alter_answer_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='section',
            field=models.CharField(blank=True, help_text='Optional heading to group this question under when reviewing or filling in the form -- e.g. "Technical skills". Leave blank to keep it ungrouped, or repeat the same heading on consecutive questions to group them together.', max_length=255, verbose_name='section'),
        ),
    ]
