# Generated by Django 6.0.6 on 2026-07-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_staff_role_cartitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(blank=True, max_length=255, verbose_name='number'),
        ),
    ]
