# Generated by Django 6.0.6 on 2026-07-12 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_familymembership_unique_together_and_more'),
        ('shop', '0007_discount_applieddiscount_invoice_orderline_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applieddiscount',
            name='applied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applied_discounts', to='members.member', verbose_name='applied by'),
        ),
    ]
