# Generated by Django 6.0.6 on 2026-07-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_familymembership_unique_together_and_more'),
        ('shop', '0008_alter_applieddiscount_applied_by'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='applieddiscount',
            constraint=models.UniqueConstraint(fields=('order', 'discount'), name='unique_discount_per_order'),
        ),
    ]
