# Generated by Django 6.0.6 on 2026-08-25 19:27

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0033_club_shop_open_shopmanager'),
        ('shop', '0010_applieddiscount_created_applieddiscount_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='pdf',
        ),
        migrations.AddField(
            model_name='discount',
            name='code',
            field=models.CharField(default='', help_text='What members type in at checkout, e.g. SUMMER10. Not case-sensitive.', max_length=50, verbose_name='code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=shop.models.product_image_path, verbose_name='photo'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='price'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.UniqueConstraint(fields=('club', 'code'), name='unique_discount_code_per_club'),
        ),
    ]
