# Generated by Django 6.0.6 on 2026-08-25 20:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_parentclaim_submitted_by_user'),
        ('shop', '0011_remove_invoice_pdf_discount_code_product_description_and_more'),
        ('teams', '0012_alter_refereelevel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. “Small”, “Medium — Red”, “XL”.', max_length=255, verbose_name='name')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text="Leave blank to use the product's own price.", max_digits=10, null=True, verbose_name='price')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active?')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='ordering')),
            ],
            options={
                'verbose_name': 'product variant',
                'verbose_name_plural': 'product variants',
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_product_per_cart_per_beneficiary',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='shop.productvariant', verbose_name='variant'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='shop.productvariant', verbose_name='variant'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product', 'variant', 'beneficiary'), name='unique_product_per_cart_per_beneficiary'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='unique_variant_name_per_product'),
        ),
    ]
