# Generated by Django 6.0.6 on 2026-08-26 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_productcategory_product_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['name'], 'verbose_name': 'product category', 'verbose_name_plural': 'product categories'},
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='ordering',
        ),
    ]
