# Generated by Django 6.0.6 on 2026-08-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_instructions',
            field=models.TextField(blank=True, help_text='Optional -- shown to the member, e.g. "ask for it at the clubhouse desk".', verbose_name='pickup instructions'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partially_paid', 'Partially paid'), ('ready_for_pickup', 'Ready for pickup'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('delivered', 'Delivered')], default='pending', max_length=255, verbose_name='status'),
        ),
    ]
