# Generated by Django 6.0.6 on 2026-08-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_order_pickup_instructions_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=255, verbose_name='payment status'),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfillment_status',
            field=models.CharField(choices=[('not_ready', 'Not ready'), ('ready_for_pickup', 'Ready for pickup'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='not_ready', max_length=255, verbose_name='fulfillment status'),
        ),
    ]
