# Generated by Django 6.0.6 on 2026-08-26 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_populate_order_payment_and_fulfillment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
