# Generated by Django 6.0.6 on 2026-08-26 13:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0033_club_shop_open_shopmanager'),
        ('members', '0006_parentclaim_submitted_by_user'),
        ('shop', '0018_remove_order_status'),
        ('teams', '0012_alter_refereelevel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, max_length=255, verbose_name='number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('consumed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='consumed amount')),
                ('expiry_date', models.DateField(verbose_name='expiry date')),
                ('is_active', models.BooleanField(default=True, help_text='Turn off to void a voucher before its expiry date, e.g. if it was issued by mistake.', verbose_name='is active?')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'voucher',
                'verbose_name_plural': 'vouchers',
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_product_per_cart_per_beneficiary',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='personalization_name',
            field=models.CharField(blank=True, help_text='Optional -- e.g. the name to print on this item.', max_length=100, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='personalization_number',
            field=models.CharField(blank=True, help_text='Optional -- e.g. the player number to print on this item.', max_length=20, verbose_name='number'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='personalization_name',
            field=models.CharField(blank=True, help_text='Optional -- e.g. the name to print on this item.', max_length=100, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='personalization_number',
            field=models.CharField(blank=True, help_text='Optional -- e.g. the player number to print on this item.', max_length=20, verbose_name='number'),
        ),
        migrations.AddField(
            model_name='product',
            name='personalization_enabled',
            field=models.BooleanField(default=False, help_text='Lets a member enter a number and/or a name to print on this item when ordering, e.g. for a jersey.', verbose_name='personalization enabled?'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('credit_card', 'Credit card'), ('bank_transfer', 'Bank transfer'), ('cash', 'Cash'), ('voucher', 'Voucher')], default='credit_card', max_length=255, verbose_name='method'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product', 'variant', 'beneficiary', 'personalization_number', 'personalization_name'), name='unique_product_per_cart_per_beneficiary'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='club.club'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='issued_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='members.member', verbose_name='issued to'),
        ),
        migrations.AddField(
            model_name='payment',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='shop.voucher', verbose_name='voucher'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.UniqueConstraint(fields=('club', 'number'), name='unique_voucher_number_per_club'),
        ),
    ]
