# Generated by Django 6.0.6 on 2026-08-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_voucher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='production_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_production', 'In production'), ('received', 'Received')], default='pending', max_length=255, verbose_name='production status'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='production_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_production', 'In production'), ('received', 'Received')], default='pending', max_length=255, verbose_name='production status'),
        ),
    ]
