# Generated by Django 6.0.6 on 2026-08-27 07:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_product_product_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherConsumption',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('note', models.TextField(help_text='What this was for, e.g. “Cash payment for the tournament fee, collected at the clubhouse.”', verbose_name='note')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='recorded at')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_consumptions_recorded', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='shop.voucher', verbose_name='voucher')),
            ],
            options={
                'verbose_name': 'voucher consumption',
                'verbose_name_plural': 'voucher consumptions',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
