# Generated by Django 6.0.6 on 2026-08-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_voucherconsumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_registrants',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Applies once a single registration includes at least this many people registering through this product.', null=True, verbose_name='minimum registrants'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_registrants_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='multi-registrant discount amount'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_registrants_discount_enabled',
            field=models.BooleanField(default=False, verbose_name='multi-registrant discount enabled?'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_registrants_discount_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed amount')], default='percentage', max_length=255, verbose_name='multi-registrant discount type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='early_bird_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='early bird discount amount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='early_bird_discount_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed amount')], default='percentage', max_length=255, verbose_name='early bird discount type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('membership', 'Membership'), ('event_fee', 'Event fee'), ('merchandise', 'Merchandise')], default='event_fee', max_length=255, verbose_name='product type'),
        ),
    ]
