# Generated by Django 6.0.6 on 2026-08-27 13:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_product_min_registrants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='min_registrants',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_registrants_discount_amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_registrants_discount_enabled',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_registrants_discount_type',
        ),
        migrations.CreateModel(
            name='ProductRegistrantDiscountTier',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_registrants', models.PositiveSmallIntegerField(help_text='Applies once a single registration includes at least this many people registering through this product.', validators=[django.core.validators.MinValueValidator(2)], verbose_name='minimum registrants')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed amount')], default='percentage', max_length=255, verbose_name='discount type')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='discount amount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrant_discount_tiers', to='shop.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'registrant discount tier',
                'verbose_name_plural': 'registrant discount tiers',
                'ordering': ['product', 'min_registrants'],
                'constraints': [models.UniqueConstraint(fields=('product', 'min_registrants'), name='unique_tier_threshold_per_product')],
            },
        ),
    ]
