# Generated by Django 6.0.6 on 2026-08-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_remove_product_min_registrants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('membership', 'Membership'), ('event_fee', 'Event fee'), ('merchandise', 'Merchandise')], default='merchandise', max_length=255, verbose_name='product type'),
        ),
    ]
