# Generated by Django 6.0.6 on 2026-08-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='registration_kind',
            field=models.CharField(blank=True, choices=[('player', 'Player'), ('volunteer', 'Volunteer')], help_text='System categories only (Player/Volunteer) -- leave blank for an ordinary category.', max_length=20, verbose_name='registration kind'),
        ),
    ]
