# Generated by Django 6.0.6 on 2026-08-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_seed_registration_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='registrant_discount_scope',
            field=models.CharField(blank=True, choices=[('per_person', 'Per person (applies to every qualifying registration)'), ('per_order', 'Per order (subtracted once)')], default='per_person', help_text='Whether a registrant-discount-tier threshold below applies to every qualifying registration, or is subtracted once from the whole batch.', max_length=20, verbose_name='multi-registrant discount scope'),
        ),
    ]
