# Generated by Django 6.0.6 on 2026-09-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0038_clubmembership_club_clubme_club_id_646d5d_idx_and_more'),
        ('members', '0006_parentclaim_submitted_by_user'),
        ('shop', '0028_product_registrant_discount_scope'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['club', '-created'], name='shop_order_club_id_db4c7a_idx'),
        ),
    ]
