# Generated by Django 6.0.6 on 2026-08-23 09:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_jobrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobToggle',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Dotted Celery task name, matching a features.jobs.JOB_REGISTRY key.', max_length=255, unique=True, verbose_name='job name')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
            ],
            options={
                'verbose_name': 'job toggle',
                'verbose_name_plural': 'job toggles',
            },
        ),
    ]
