# Generated by Django 6.0.6 on 2026-08-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_jobtoggle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrun',
            name='detail',
            field=models.TextField(blank=True, help_text='What the job returned, on success.', verbose_name='detail'),
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='error',
            field=models.TextField(blank=True, help_text='What the job raised, on failure.', verbose_name='error'),
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='name',
            field=models.CharField(help_text='Matches a features.jobs.JOB_REGISTRY key, e.g. billing.tasks.renew_subscriptions.', max_length=255, verbose_name='job name'),
        ),
        migrations.AlterField(
            model_name='jobtoggle',
            name='name',
            field=models.CharField(help_text='Matches a features.jobs.JOB_REGISTRY key.', max_length=255, unique=True, verbose_name='job name'),
        ),
    ]
