# Generated by Django 6.0.6 on 2026-08-25 06:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_alter_jobrun_detail_alter_jobrun_error_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSuppression',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_suppression_windows', to=settings.AUTH_USER_MODEL, verbose_name='started by')),
            ],
            options={
                'verbose_name': 'email suppression',
                'verbose_name_plural': 'email suppression',
            },
        ),
    ]
