# Generated by Django 6.0.6 on 2026-07-05 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_family_name_alter_familymembership_family_and_more'),
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmembership',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='club.club'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubmembership',
            name='license',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubmembership',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='member_of', to='authentication.member'),
            preserve_default=False,
        ),
    ]
