# Generated by Django 6.0.6 on 2026-07-05 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_family_name_alter_familymembership_family_and_more'),
        ('club', '0002_clubmembership_club_clubmembership_license_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubmembership',
            options={'ordering': ['club', 'member__last_name', 'member__first_name'], 'verbose_name': 'club membership', 'verbose_name_plural': 'club memberships'},
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='clubmembership',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='club.club', verbose_name='club'),
        ),
        migrations.AlterField(
            model_name='clubmembership',
            name='license',
            field=models.CharField(max_length=250, verbose_name='license'),
        ),
        migrations.AlterField(
            model_name='clubmembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_of', to='authentication.member', verbose_name='member'),
        ),
        migrations.AlterUniqueTogether(
            name='clubmembership',
            unique_together={('club', 'member')},
        ),
    ]
