# Generated by Django 6.0.6 on 2026-07-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_alter_clubmembership_options_alter_club_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmembership',
            name='license',
            field=models.CharField(blank=True, max_length=250, verbose_name='license'),
        ),
    ]
