# Generated by Django 6.0.6 on 2026-07-11 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_alter_clubmembership_license'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_of', to='members.member', verbose_name='member'),
        ),
    ]
