# Generated by Django 6.0.6 on 2026-07-12 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_club_slug_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmembership',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='club.season', verbose_name='season'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clubmembership',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='club.club'),
        ),
    ]
