# Generated by Django 6.0.6 on 2026-07-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_clubmembership_season_alter_clubmembership_club'),
        ('members', '0002_alter_familymembership_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clubmembership',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='clubmembership',
            name='activated_at',
            field=models.DateField(blank=True, null=True, verbose_name='activated at'),
        ),
        migrations.AddField(
            model_name='clubmembership',
            name='fee_status',
            field=models.CharField(choices=[('unpaid', 'unpaid'), ('paid', 'paid'), ('partially_paid', 'partially paid'), ('waived', 'waived')], default='unpaid', max_length=250, verbose_name='fee status'),
        ),
        migrations.AddField(
            model_name='clubmembership',
            name='signed_up_at',
            field=models.DateField(blank=True, null=True, verbose_name='signed up at'),
        ),
        migrations.AddField(
            model_name='clubmembership',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('pending', 'pending'), ('lapsed', 'lapsed'), ('cancelled', 'cancelled')], default='pending', max_length=250, verbose_name='status'),
        ),
        migrations.AddConstraint(
            model_name='clubmembership',
            constraint=models.UniqueConstraint(fields=('club', 'member', 'season'), name='unique_member_per_club_per_season'),
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(fields=('club', 'start_date', 'end_date'), name='unique_season_dates_per_club'),
        ),
    ]
