# Generated by Django 6.0.6 on 2026-07-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_clubrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='Archived clubs stop resolving on their subdomain, but their data is retained.', null=True, verbose_name='archived at'),
        ),
    ]
