# Generated by Django 6.0.6 on 2026-07-24 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0013_club_created_club_modified_clubmembership_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='secondary_color',
            field=models.CharField(blank=True, help_text="Hex colour for highlights on the club's pages, e.g. avatar initials. Defaults to the theme's secondary colour.", max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Enter a colour as a hex value, e.g. #be185d.')], verbose_name='secondary colour'),
        ),
    ]
