# Generated by Django 6.0.6 on 2026-08-03 14:30

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0016_clubmembership_amount_paid_clubmembership_fee_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='season_duration_months',
            field=models.PositiveSmallIntegerField(default=12, help_text='How many months a season lasts, counted from its start date.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='season duration (months)'),
        ),
        migrations.AddField(
            model_name='club',
            name='season_start',
            field=models.DateField(default=datetime.date(2000, 8, 1), help_text='Which day of the year a season begins — only the month and day are used, the year is ignored.', verbose_name='season start'),
        ),
    ]
