# Generated by Django 6.0.6 on 2026-08-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0017_club_season_duration_months_club_season_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='sport_type',
            field=models.CharField(choices=[('ice_hockey', 'Ice hockey'), ('other', 'Other')], default='other', help_text='Which sport this club plays -- determines which competitions and score fetchers are relevant to it.', max_length=20, verbose_name='sport'),
        ),
    ]
