# Generated by Django 6.0.6 on 2026-08-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0020_sponsor_logo_height_sponsor_logo_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='legal_name',
            field=models.CharField(blank=True, help_text='Full registered name (e.g. including a legal form like VZW/ASBL), used on official documents. Falls back to the name above when left blank.', max_length=255, verbose_name='legal name'),
        ),
    ]
