# Generated by Django 6.0.6 on 2026-08-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0021_club_legal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmembership',
            name='kind',
            field=models.CharField(choices=[('member', 'member'), ('guardian', 'guardian')], default='member', help_text="A guardian is attached to the club only as a parent of a member -- they hold the login, but don't count as a member themselves and owe no fee. A parent who also plays is a member.", max_length=20, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='club',
            name='legal_name',
            field=models.CharField(blank=True, help_text='Full registered name (e.g. including a legal form like VZW/ASBL), used on official documents. Falls back to club name if blank.', max_length=255, verbose_name='legal name'),
        ),
    ]
