# Generated by Django 6.0.6 on 2026-08-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0023_backfill_guardian_memberships'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='contact_email',
            field=models.EmailField(blank=True, help_text="The club's public address, shown to people the club writes to or asks to get in touch -- e.g. a parent claiming a child. Falls back to nothing being shown at all, so it's worth setting.", max_length=254, verbose_name='contact email'),
        ),
    ]
