# Generated by Django 6.0.6 on 2026-08-17 11:39

import club.models
import rosterchief.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0025_onboardingrequirement_memberrequirementstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberrequirementstatus',
            name='is_bypassed',
            field=models.BooleanField(default=False, verbose_name='bypassed'),
        ),
        migrations.AddField(
            model_name='onboardingrequirement',
            name='blocked_event_kinds',
            field=models.JSONField(blank=True, default=list, help_text="Event kinds a member can't be invited to or selected for while this is open. Empty means purely informational.", verbose_name='blocks selection for'),
        ),
        migrations.AlterField(
            model_name='clubrole',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('member', 'member'), ('editor', 'editor'), ('member_admin', 'member admin')], default='member', max_length=250, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='memberrequirementstatus',
            name='document',
            field=models.FileField(blank=True, help_text="Stored privately -- readable only through this member's own page, never a direct link.", storage=rosterchief.storage.PrivateStorage(location='/Users/bernard/Code/PycharmProjects/RosterChief/private_media'), upload_to=club.models.onboarding_document_path, verbose_name='document'),
        ),
    ]
