# Generated by Django 6.0.6 on 2026-08-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0026_memberrequirementstatus_is_bypassed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='website',
            field=models.URLField(blank=True, help_text="The club's own site, if it has one -- shown alongside its RosterChief pages, not used for anything else yet.", verbose_name='website'),
        ),
    ]
