# Generated by Django 6.0.6 on 2026-08-20 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0027_club_website'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onboardingrequirement',
            options={'ordering': ['name'], 'verbose_name': 'onboarding requirement', 'verbose_name_plural': 'onboarding requirements'},
        ),
        migrations.RemoveField(
            model_name='onboardingrequirement',
            name='order',
        ),
    ]
