# Generated by Django 6.0.6 on 2026-08-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0029_duesinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='legal_address',
            field=models.CharField(blank=True, help_text="Street address for official documents (invoices, the referee payment form). Falls back to the home location's address when left blank -- set this when the club's registered address isn't where it actually plays.", max_length=255, verbose_name='legal address'),
        ),
        migrations.AddField(
            model_name='club',
            name='legal_city',
            field=models.CharField(blank=True, max_length=255, verbose_name='legal city'),
        ),
        migrations.AddField(
            model_name='club',
            name='legal_zip_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='legal zip code'),
        ),
    ]
