# Generated by Django 6.0.6 on 2026-08-21 16:10

import club.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0030_club_legal_address_club_legal_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='event_background',
            field=models.ImageField(blank=True, help_text='A generic background photo for event screens in the mobile app, shown in black & white under a dark gradient. Without one, a plain dark background is used.', upload_to=club.models.club_event_background_path, verbose_name='event background'),
        ),
    ]
