# Generated by Django 6.0.6 on 2026-08-23 18:57

import club.models
import rosterchief.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0031_club_event_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrequirementstatus',
            name='document',
            field=models.FileField(blank=True, help_text="Stored privately -- readable only through this member's own page, never a direct link.", storage=rosterchief.storage.get_private_storage, upload_to=club.models.onboarding_document_path, verbose_name='document'),
        ),
    ]
