# Generated by Django 6.0.6 on 2026-08-25 19:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0032_alter_memberrequirementstatus_document'),
        ('members', '0006_parentclaim_submitted_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='shop_open',
            field=models.BooleanField(default=False, help_text="While off, the shop is hidden from the member app entirely and the management panel's shop screens are read-only for browsing but refuse new orders.", verbose_name='shop open'),
        ),
        migrations.CreateModel(
            name='ShopManager',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='club.club')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_manager_grants', to='members.member', verbose_name='member')),
            ],
            options={
                'verbose_name': 'shop manager',
                'verbose_name_plural': 'shop managers',
                'ordering': ['club', 'member__last_name', 'member__first_name'],
                'constraints': [models.UniqueConstraint(fields=('club', 'member'), name='unique_shop_manager_per_club')],
            },
        ),
    ]
