# Generated by Django 6.0.6 on 2026-08-27 12:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0033_club_shop_open_shopmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmembership',
            name='early_payment_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='early payment deadline'),
        ),
        migrations.AddField(
            model_name='clubmembership',
            name='early_payment_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='early payment discount'),
        ),
    ]
