# Generated by Django 6.0.6 on 2026-08-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0034_clubmembership_early_payment_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='payment_instructions',
            field=models.TextField(blank=True, help_text='How to pay a fee (e.g. bank account/IBAN, or a preferred method) -- shown on the mobile Payments & dues page and the registration status page, and included on registration invoices. Falls back to nothing shown when left blank.', verbose_name='payment instructions'),
        ),
    ]
