# Generated by Django 6.0.6 on 2026-08-31 18:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0035_club_payment_instructions'),
        ('members', '0006_parentclaim_submitted_by_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationManager',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='club.club')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_manager_grants', to='members.member', verbose_name='member')),
            ],
            options={
                'verbose_name': 'evaluation manager',
                'verbose_name_plural': 'evaluation managers',
                'ordering': ['club', 'member__last_name', 'member__first_name'],
                'constraints': [models.UniqueConstraint(fields=('club', 'member'), name='unique_evaluation_manager_per_club')],
            },
        ),
    ]
