# Generated by Django 6.0.6 on 2026-09-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0036_evaluationmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='vat_id',
            field=models.CharField(blank=True, help_text='VAT/tax registration number, if the club has one. Shown on invoices sent to or by the club when set.', max_length=32, verbose_name='VAT ID'),
        ),
    ]
