# Generated by Django 6.0.6 on 2026-09-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0037_club_vat_id'),
        ('members', '0006_parentclaim_submitted_by_user'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clubmembership',
            index=models.Index(fields=['club', 'season', 'kind'], name='club_clubme_club_id_646d5d_idx'),
        ),
        migrations.AddIndex(
            model_name='clubmembership',
            index=models.Index(fields=['club', 'season', 'status'], name='club_clubme_club_id_4f53de_idx'),
        ),
        migrations.AddIndex(
            model_name='duesinvoice',
            index=models.Index(fields=['club', 'sent_at'], name='club_duesin_club_id_b6d41e_idx'),
        ),
    ]
