# Generated by Django 6.0.6 on 2026-09-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0038_clubmembership_club_clubme_club_id_646d5d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='contact_email',
            field=models.EmailField(blank=True, help_text="The club's public address, shown to people the club writes to or asks to get in touch. Falls back to nothing being shown at all, so it's worth setting.", max_length=254, verbose_name='contact email'),
        ),
    ]
