# Generated by Django 6.0.6 on 2026-07-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='familymembership',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='familymembership',
            constraint=models.UniqueConstraint(fields=('family', 'member'), name='unique_member_per_family'),
        ),
    ]
