# Generated by Django 6.0.6 on 2026-08-11 14:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0023_backfill_guardian_memberships'),
        ('members', '0004_group_groupmembership_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentClaim',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_first_name', models.CharField(max_length=150, verbose_name='parent first name')),
                ('parent_last_name', models.CharField(max_length=150, verbose_name='parent last name')),
                ('parent_email', models.EmailField(max_length=254, verbose_name='parent email')),
                ('child_first_name', models.CharField(max_length=150, verbose_name='child first name')),
                ('child_last_name', models.CharField(max_length=150, verbose_name='child last name')),
                ('child_date_of_birth', models.DateField(verbose_name='child date of birth')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=20, verbose_name='status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('note', models.TextField(blank=True, help_text='Why it was rejected, or anything worth recording about the decision.', verbose_name='note')),
                ('child', models.ForeignKey(blank=True, help_text='Set when an admin approves the claim -- the child it was matched to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_claims', to='members.member', verbose_name='matched child')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='club.club')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='members.member', verbose_name='reviewed by')),
            ],
            options={
                'verbose_name': 'parent claim',
                'verbose_name_plural': 'parent claims',
                'ordering': ['-created'],
            },
        ),
    ]
