# Generated by Django 6.0.6 on 2026-09-12 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_family_club'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParentClaim',
        ),
    ]
