# Generated by Django 6.0.6 on 2026-09-13 17:59

import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_delete_parentclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, upload_to=members.models.member_photo_path, verbose_name='photo'),
        ),
        migrations.AddField(
            model_name='member',
            name='photo_public_consent',
            field=models.BooleanField(default=False, verbose_name='show this photo on the public website/API'),
        ),
    ]
