# Generated by Django 6.0.6 on 2026-09-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0038_clubmembership_club_clubme_club_id_646d5d_idx_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('members', '0006_parentclaim_submitted_by_user'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['club', 'member', 'read_at'], name='notificatio_club_id_82f4ae_idx'),
        ),
    ]
