# Generated by Django 6.0.6 on 2026-09-05 16:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0037_club_vat_id'),
        ('members', '0006_parentclaim_submitted_by_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10, verbose_name='priority')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('in_progress', 'In progress'), ('fixed', 'Fixed'), ('wont_fix', "Won't fix")], default='submitted', max_length=20, verbose_name='status')),
                ('fixed_at', models.DateTimeField(blank=True, null=True, verbose_name='fixed at')),
                ('fixed_version', models.CharField(blank=True, help_text='Version/release this was fixed in -- shown back to the reporter once status is Fixed.', max_length=50, verbose_name='fixed in version')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='club.club')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_reports', to='members.member', verbose_name='reported by')),
            ],
            options={
                'verbose_name': 'bug report',
                'verbose_name_plural': 'bug reports',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='BugNote',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(verbose_name='note')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='bugs.bugreport', verbose_name='bug report')),
            ],
            options={
                'verbose_name': 'bug note',
                'verbose_name_plural': 'bug notes',
                'ordering': ['created'],
            },
        ),
    ]
